#include 	"xplot_ext.h"

extern int shift_signal;

EventLoop(frame)
Frame	*frame;
{
XEvent		event; 
WindowData	*data;
Graph 		*graph;
extern char *restorefile;
char		verstr[100];

    XFlush(frame->display);
    graph = frame->graph;
    RescaleFrame(frame);
    /*
    ** display the graph
    */
    sprintf(verstr,"XPLOT v%s %s",VERSION,COPYRIGHT);
    AddLabelString(frame->text,verstr,
    frame->text->fontwidth,frame->text->fontheight,0.0,0.0,
    SCREEN_LBL,TEMPORARY_LBL,frame->fontname);

    /*
    ** execute command file or line if any
    */
    ExecuteCommands(graph);

    /*
    ** process any pending events
    */
    while(XPending(frame->display)){
	ProcessEvent(frame);
    }
    RescaleFrame(frame);

    MapWindows(frame);

    if(restorefile){
	if(F->display && F->width > 0 && F->height > 0){
	    XResizeWindow(F->display,F->window,F->width,F->height);
	    XFlush(frame->display);
	    RescaleFrame(frame);
	}
    }

    while(1){
    if(shift_signal){
	RightShift();
	shift_signal = 0;
    }
	ProcessEvent(frame);
	/*
	if(data->id == FRAME_WINDOW){
	    if(debug){
		printf("FRAME ");
		EventString(&event);
	    }
	    data->func(data->parent,&event);
	    frame_event(data->parent,&event);
	} else
	if(data->id == GRAPH_WINDOW){
	    if(debug){
		printf("GRAPH ");
		EventString(&event);
	    }
	    graph_event(data->parent,&event);
	} else
	if(data->id == TEXT_WINDOW){
	    if(debug){
		printf("TEXT ");
		EventString(&event);
	    }
	    text_event(data->parent,&event);
	} else
	if(data->id == MENU_WINDOW){
	    if(debug){
		printf("MENU ");
		EventString(&event);
	    }
	    menu_event(data->parent,&event);
	}
	*/
    }
}

ProcessEvent(frame)
Frame	*frame;
{
WindowData	*data;
XEvent		event; 

    XNextEvent(frame->display,&event);
    /*
    ** get data from the window the event occured in
    */
    XFindContext(frame->display,((XKeyEvent *)(&event))->window,
	datacontext,(XPointer *) &data);
    if(debug){
	fprintf(stderr,"window %s\n",data->parent->windowname);
    }
    data->func(data->parent,&event);
}

frame_event(frame,event)
Frame		*frame;
XEvent		*event;
{
int stat;

    switch (event->type) {
    case ConfigureNotify:
	XSynchronize(frame->display,1);
	stat = RescaleFrame(frame);
	XSynchronize(frame->display,0);
	if(stat){
	    /*
	    ** get rid of the unpredictable refreshes generated by the 
	    ** reconfigure
	    */
	    ZapExpose(frame->display);
	    /*
	    ** refresh the subwindows myself
	    */
	    RefreshGraph(frame->graph);
	    RefreshText(frame->text);
	    RefreshMenu(frame->menu);
	}
	break;
    default:
	break;
    }
}

graph_event(graph,event)
Graph		*graph;
XEvent		*event;
{
XExposeEvent	*xev;

    switch (event->type) {
    case Expose:
	xev = (XExposeEvent *)event;
	if(xev->count == 0){
	    RefreshGraph(graph);
	}
	break;
    case ButtonPress:
	ButtonPressAction(graph,event);
	break;
    case ButtonRelease:
	ButtonReleaseAction(graph,event);
	break;
    case KeyPress:
	KeyAction(graph,event);
	break;		
    case MotionNotify :
	PointerMotionAction(graph,event);
	break;		
    default:
	break;
    }
}

text_event(text,event)
TextWindow	*text;
XEvent		*event;
{
XExposeEvent	*xev;

    switch (event->type) {
    case Expose:
	xev = (XExposeEvent *)event;
	if(xev->count == 0){
	    RefreshText(text);
	}
	break;
    default:
	break;
    }
}

menu_event(menu,event)
MenuWindow	*menu;
XEvent		*event;
{
XExposeEvent	*xev;

    if(debug){
	fprintf(stderr,"menu action %d\n",event->type);
    }
    switch (event->type) {
    case Expose:
	xev = (XExposeEvent *)event;
	if(xev->count == 0){
	    RefreshMenu(menu);
	}
	break;
    default:
	break;
    }
}

EventString(E)
XEvent	*E;
{
XButtonPressedEvent	*B;
static int count=0;

    printf("%d ",count);
    switch(E->type){
    case ButtonPress :
	B = (XButtonPressedEvent *)E;
	printf("ButtonPress ");
	if(B->button == 1){
	   printf("1 "); 
	} 
	if(B->button == 2){
	   printf("2 "); 
	} 
	if(B->button == 3){
	   printf("3"); 
	} 
	printf("\n");
	break;
    case ButtonRelease :
	B = (XButtonPressedEvent *)E;
	printf("ButtonRelease ");
	if(B->button == 1){
	   printf("1 "); 
	} 
	if(B->button == 2){
	   printf("2 "); 
	} 
	if(B->button == 3){
	   printf("3"); 
	} 
	printf("\n");
	break;
    case MotionNotify :
	printf("PointerMoved %d %d\n",
	((XPointerMovedEvent *)E)->state,
	((XPointerMovedEvent *)E)->is_hint);
	break;
    case Expose :
	printf("Expose %d\n",((XExposeEvent *)E)->count);
	break;
    case KeyPress :
	printf("KeyPress\n");
	break;
    case ConfigureNotify:
	printf("Configure\n");
	break;
    default:
	printf("unknown event type %d\n",E->type);
	break;
    }
    count++;
}

