#!/usr/bin/python

import os 
import shutil
from subprocess import call 
import filecmp
import sys


##############################
# Define data files
##############################
eegFiles = { 'raw' 	:  './tests/data/original.eeg.raw', 
			 'ad-ext'	: './tests/data/original.eeg'}

posFiles = { 'raw'		: './tests/data/original.pos.raw',
			 'ad-ext'	: './tests/data/original.pos',
			 'pos-ext'	: './tests/data/original.p'}

spkFiles = { 'raw'		: './tests/data/original.tt.raw',
			 'ad-ext' 	: './tests/data/original.tt'}

ttFiles  = {'tt'	: './tests/data/original2.tt',
			'parm'	: './tests/data/original2.pxyabw',
			'cb'	: './tests/data/original2.cb',
			'ave'	: './tests/data/original2.ave'}

tmpDir = '/tmp/mwltemp/'
cmdLog = 'test.log'

global nFail, nPass
nFail = 0
nPass = 0


def runTests():
	mkTmpDir()
	testExtractEEG()
	testExtractPos1()
	testExtractPos2()
	testExtractTet()
	testSpikeParms()
	testSpikeAve()

	report()

def testExtractEEG():
	print 'ADEXTRACT  EEG...', 
	
	outFile = tmpDir + 'test.eeg';
	cmd = './build/bin/adextract -eslen80 ' + eegFiles['raw'] + ' -c' + ' -o ' + outFile
	executeTest(cmd, eegFiles['ad-ext'], outFile)
	
def testExtractPos1():
	print 'ADEXTRACT  POS...',
	
	outFile = tmpDir + 'test.pos'
	cmd = './build/bin/adextract ' + posFiles['raw'] + ' -p -o ' + outFile
	executeTest(cmd, posFiles['ad-ext'], outFile);

def testExtractPos2():
	print 'POSEXTRACT POS...',

	outFile = tmpDir + 'test.p';
	cmd = './build/bin/posextract ' + posFiles['ad-ext'] + ' -o ' + outFile
	executeTest(cmd, posFiles['pos-ext'], outFile)

def testExtractTet():
	print 'ADEXTRACT  TET...',

	outFile = tmpDir + 'test.tt'
	cmd = './build/bin/adextract -eslen80 ' + spkFiles['raw'] + ' -t -probe 0 -o ' + outFile
	executeTest(cmd, spkFiles['ad-ext'], outFile)

def testSpikeParms():
	print 'SPIKEPARMS TET...',

	outFile = tmpDir + 'test.pxyabw'
	cmd = './build/bin/spikeparms2 ' + ttFiles['tt'] + ' -tetrode -parms t_px,t_py,t_pa,t_pb -o ' + outFile
	executeTest(cmd, ttFiles['parm'], outFile)	

def testSpikeAve():
	print 'SPIKEAVGE  TET..',

	outFile = tmpDir + 'test.ave'
	cmd = './build/bin/spikeavg ' + ttFiles['tt'] + ' -if ' + ttFiles['cb'] + ' > ' + outFile
	
	executeTest(cmd, ttFiles['ave'], outFile)	

def executeTest(cmd, orig, new):
	with open('/dev/null', "w") as fnull:
		result = call(cmd, shell=True, stdout = fnull, stderr = fnull)

	ex = os.path.isfile(new)

	if not ex:
		failTest()
		print result, cmd
		return;

	sz = os.stat(new).st_size;
	if sz == 0:
		failTest()
		print result, cmd
		return;

	if areSameFile(orig, new):
		passTest()
	else:
		failTest()
		print result, cmd
		return

def areSameFile(orig, new):
	out = [tmpDir + 'out1', 	tmpDir + 'out2']
	
	cmd = [ "sed '1,/%%ENDHEADER/ d' " + orig + ' > ' + out[0], 
		    "sed '1,/%%ENDHEADER/ d' " + new + ' > ' + out[1] ]
	
	call([cmd[0]], shell=True)
	call([cmd[1]], shell=True)
	
	return filecmp.cmp(out[0], out[1])

def mkTmpDir():
	if not os.path.isdir(tmpDir):
		os.makedirs(tmpDir)

def rmTmpDir():
	if os.path.isdir(tmpDir):
		shutil.rmtree(tmpDir)	

def passTest():
	print '\033[92m' + '\tPASSED!' +  '\033[0m'
	global nPass
	nPass+=1
def failTest():
	print '\033[91m' + '\tFAILED!' +  '\033[0m'
	global nFail
	nFail+=1

def report():
	print '   \033[92mPASSED:' + str(nPass) + '   \033[91mFAILED:' + str(nFail)  + '\033[0m'

if __name__ =='__main__':
	runTests()

