typedef struct range_type {
    unsigned long	stime;	
    unsigned long	etime;	
} Range;

typedef struct timbinstatus_type {
    unsigned char	valid;
} TimeBinStatus;

typedef struct corr_result_type {
    int		nbins;
    int		zbin;
    float	peakcorr;
    float	zerocorr;
    int		peakphase;
    float	meanphase;
    float	distance;
    int		totalcount;
    int		valid;
    float	expected_corr;
    float	sd_corr;
    float	meanrate;
    float	minrate;
    float	maxrate;
} CorrResult;

typedef struct clusterdir_type {
    char	path[80];
    char	dirname[80];
    char	filename[40];
    short	clusterid;
    short	ignore;
    float	parameter;
} ClusterDir;

typedef struct position_type {
    float		x;
    float		y;
} Position;

typedef struct dual_position_type {
    float		x;
    float		y;
    float		x2;
    float		y2;
} DualPosition;

typedef struct grid_position_type {
    int		x;
    int		y;
} GridPosition;

typedef struct tnode_type {
    struct tnode_type	*next;
    struct tnode_type	*child;
    short		id;
    int			ntraversals;
    float		px,py;
    float		pcumdistance;
    int			npositions;
} TNode;

typedef struct corrlist_type {
    int		index;
    float	corrsum;
} CorrList;

typedef struct result_type {
    int		nclusters;
    int		nreconclusters;
    int		ntimebins;
    int		nrecontimebins;
    unsigned long	tstart;
    unsigned long 	tend;
    unsigned long	recontstart;
    unsigned long 	recontend;
    long	binsize;
    unsigned long 	**spikearray;
    float 	**datavector;
    float 	**reconvector;
    float 	*datasum;
    float 	*datasqr;
    float	*valcorr;
    int		*nvalcorr;
    int		*spikecount;
    int		*reconspikecount;
    int		xmax;
    int		ymax;
    int		xlo;
    int		ylo;
    int		xhi;
    int		yhi;
    int		gxlo;
    int		gylo;
    int		gxhi;
    int		gyhi;
    int		datatype;
    float	**corrmatrix;
    float	***positiongrid;
    float	***positiongridzero;
    float	**corrgrid;
    float	**smoothcorrgrid;
    float	**maggrid;
    float	**truemaggrid;
    float	**sparsegrid;
    float	**perrgrid;
    float	**smoothperrgrid;
    float	**occgrid;
    float	**trueoccgrid;
    float	*sparsevec;
    int		normalize;
    int		peaknormalize;
    int		lump;
    int		hasposition;
    int		hasspatialfiring;
    ClusterDir	*pdir;
    FILE	*fppout;
    FILE	*fpcorrout;
    FILE	*fppdir;
    FILE	*fpdir;
    FILE	*fpdirrecon;
    FILE	*fpout;
    FILE	*fpmagout;
    FILE	*fpsparsegridout;
    FILE	*fpsparsevecout;
    FILE	*fppopvecout;
    FILE	*fppfile;
    FILE	*fpperrgrid;
    FILE	*fppouterr;
    FILE	*fptreeout;
    FILE	*fpreplayout;
    FILE	*fpreplaydot;
    FILE	*fpreplaycorr;
    FILE	*fpspikecorr;
    FILE	*fpfieldcenter;
    FILE	*fpcorrplotout;
    FILE	*fpcorrmatrixout;
    FILE	*fpstatout;
    FILE	*fpcorrhistout;
    FILE	*fppoptrainout;
    FILE	*fpspiketrainout;
    FILE	*fprange;
    FILE	*fpdout;
    FILE	*fpspeedout;
    FILE	*fpparms;
    FILE	*fperr;
    FILE	*fpbayesianout;
    float	*peak;
    GridPosition	*peakloc;
    float	sparsity_cutoff;
    int		nactivep;
    int		nactivec;
    int		nreconactivec;
    int		comparepositions;
    DualPosition	*position;
    Position	*calcposition;
    float	*speed;
    int		smoothgrid;
    int		smoothcorr;
    float	meanpositionerror;
    int		ambiguous;
    int		nambiguous;
    float	minpeak;
    int		minspikes;
    int		maxspikes;
    float	minrate;
    float	maxrate;
    int		occcutoff;
    float	fraction;
    int		useallclusters;
    int		maxtraversal;
    int		traversal_threshold;
    TNode	*trajectory_tree;
    int		treeoutputformat;
    int		replay_threshold;
    int		spike_bin_offset;
    int		position_bin_offset;
    int		position_bin_search;
    int		position_bin_avg;
    int		suppress_replay_firing;
    int		replay_optimize;
    int		tmax;
    int		peak_search_window;
    int		min_corr_events;
    int		min_totalcorr_events;
    int		peakwidth;
    float	peakcutoff;
    double	*binmean;
    double	*binsd;
    char	**clustername;
    int		withinprobe;
    int		betweenprobe;
    int		showallcorrs;
    float	peakfrac;
    float	corrtest;
    int		has_tstart;
    int		has_tend;
    int		reconhas_tstart;
    int		reconhas_tend;
    int		gerstein;
    int		bayesian;
    int		make_trajectory_tree;
    int		requested_node_id;
    int		reconstruct;
    int		replay_fields;
    int		spike_correlations;
    CorrList	*corrlist;
    int		sortcorr;
    int		pshuffle;
    int		vshuffle;
    int		nranges;
    int		nreconranges;
    int		maxranges;
    Range	*range;
    Range	*reconrange;
    TimeBinStatus	*timebinstatus;
    int		corrhistsignbias;
    int		loadspikes;
    int		binspikes;
    int		skew_window;
    int		hasparameters;
    int		popthresh;
    float	zerosqueeze;
    int		skewnormalize;
    int		skewcount;
    int		limitclusters;
    int		xresolution;
    int		yresolution;
    int		spatially_restrict_corr;
    char	prefix[80];
    int		useprefix;
    int		rawhist;
    int		posinterpolate;
    int		smoothspikes;
    int		asciiout;
    float	*zerop;
    float	*nonzerop;
    int		ntotalocc;
    float	zerolevel;
} Result;

