### MWL Makefile includes

# needed by include files
TOPDIR = ../../

# include commonly used definitions (CC,INCLUDE, LIBS etc...) and
# cflags (Date, RPM name ...)
include $(TOPDIR)definitions.mk

all: $(ALL)
	echo $(CFLAGS)
