Summary: Matt Wilson's lab software
Name: mwl-wilson-software
Version: 1.2
Release: 1
License: GPL
Group: MWL
Prefix: /usr
Obsoletes: mwl-wilson-libs
Obsoletes: mwl-wilson-utils
Obsoletes: mwl-wilson-extract
Obsoletes: mwl-wilson-xclust
URL: http://mwl.mwl.ai.mit.edu/
Source0: mwl-wilson-software.tar.gz
BuildRoot: %{_tmppath}/%{name}-buildroot
BuildArch: i386

%define debug_package %{nil}

%description
All software necessary to extract / cluster / analyze spike/eeg data. Includes: adextract, xclust, and much more.


#### PREP
%prep
rm -Rf $RPM_BUILD_ROOT
mkdir $RPM_BUILD_ROOT


#### SETUP
%setup -n mwl-wilson-software

#make the file list by finding all files in mwl-wilson-software and prepending /usr/
cd $RPM_BUILD_DIR/%{name}
find * -type f | awk '/./{print "/usr/" $1}' > filelist

#### BUILD
%build

#### PRE-INSTALL
%pre

#### INSTALL
%install
rm -rf $RPM_BUILD_ROOT

mkdir -p $RPM_BUILD_ROOT/usr/bin
cp -rf $RPM_BUILD_DIR/mwl-wilson-software/bin/* $RPM_BUILD_ROOT/usr/bin

mkdir -p $RPM_BUILD_ROOT/usr/share/doc/%{name}-%{version}-%{release}
cp -rf $RPM_BUILD_DIR/mwl-wilson-software/share/doc/%{name}-%{version}-%{release}/* $RPM_BUILD_ROOT/usr/share/doc/%{name}-%{version}-%{release}

#### POST-INSTALL
%post

ln -sf /usr/bin/adextract /usr/bin/adextract80

#### PRE-UNINSTALL
%preun


#### POST-UNINSTALL
%postun
if [ "$1" = "0" ] ; then # last uninstall
rm -f /usr/bin/adextract80
fi


%clean rm -rf $RPM_BUILD_ROOT


# * * * * * * * * * * *
# the file list is generated by the Makefile, so if the install
# location changes, be sure to change the relevant environment
# variables there.
%files -f filelist
%defattr(-,root,root)
%doc /usr/share/doc/%{name}-%{version}-%{release}




%changelog
* Wed Feb 16 2005  <tjd@blakey.mwl.ai.mit.edu> 1.2-1
- Release version. First release of xclust3

* Mon Feb 14 2005  <tjd@blakey.mwl.ai.mit.edu> 1.1-2.93
- fixed partialplotload bug - Release Candidate

* Sun Feb 13 2005  <tjd@blakey.mwl.ai.mit.edu> 1.1-2.92
- beta as of 020514 (Tom's lab meeting)

* Tue Jan 11 2005  <tjd@blakey.mwl.ai.mit.edu> 1.1-2.90
- beta release before 1.2-1 - lots of changes/fixes!

* Mon Nov 29 2004 Tom Davidson <tjd@localhost.localdomain> - 1.1-2
- release 2. behav bugfix, see RELEASE

* Mon Nov 22 2004  <tjd@blakey.mwl.ai.mit.edu> 1.1-1
- don't distribute any libs
- distribute release notes and changelog as 'doc' files

* Thu Nov 11 2004  <tjd@blakey.mwl.ai.mit.edu> 1.0-1
- initial build
- new monolithic wilson lab software RPM
